#!/usr/bin/env python3
"""
build_protonation_state.py

Builds a starting geometry for a deprotonated microstate of a diprotic
molecule (developed for artepilin C: carboxylic acid + phenol) by
removing one or two hydroxyl hydrogens from a neutral reference .xyz,
and writes the result into a new folder alongside a Turbomole 'coord'
file (via xyz_to_coord.py) and a CHARGE.txt note.

Which O-H hydrogens are removal candidates is detected automatically
from geometry, not hardcoded atom indices: an O bonded to exactly one C
and one H is a hydroxyl; if that C also has a second O neighbor within
carbonyl bonding distance (< 1.35 A), the hydroxyl is classified
'carboxylic', otherwise 'other' (e.g. phenolic). This assumes exactly
two hydroxyls in the neutral structure -- true for artepilin C, but not
general. Always run --list-oh first on a new molecule/geometry to
confirm the classification before trusting --remove.

Usage:
    # inspect detected hydroxyls first, writes nothing
    python ~/work_turbomole/scripts/build_protonation_state.py \
        --xyz structure.xyz --list-oh

    # carboxylate monoanion (tautomer A, dominant at physiological pH)
    python ~/work_turbomole/scripts/build_protonation_state.py \
        --xyz structure.xyz --remove carboxylic \
        --output-dir artepillin_c_monoanion_a_d3_hse06

    # phenolate monoanion (tautomer B, minor)
    python ~/work_turbomole/scripts/build_protonation_state.py \
        --xyz structure.xyz --remove other \
        --output-dir artepillin_c_monoanion_b_d3_hse06

    # dianion
    python ~/work_turbomole/scripts/build_protonation_state.py \
        --xyz structure.xyz --remove carboxylic other \
        --output-dir artepillin_c_dianion_d3_hse06

The output folder name is left entirely up to --output-dir (not
generated by this script) so it can be pointed at whichever
'<state>_d3_<functional>'-style directory a later production run at a
different functional needs -- the deprotonated geometry itself does
not depend on the DFT functional.
"""

import argparse
import os
import subprocess

CARBONYL_BOND_MAX = 1.35   # Angstrom, C=O
CO_BOND_MAX = 1.75         # Angstrom, generic C-O single/aromatic bond
OH_BOND_MAX = 1.15         # Angstrom, O-H


def read_xyz(xyz_path):
    with open(xyz_path) as f:
        lines = [line.rstrip("\n") for line in f]
    natoms = int(lines[0].split()[0])
    atoms = []
    for line in lines[2:2 + natoms]:
        parts = line.split()
        symbol = parts[0]
        x, y, z = map(float, parts[1:4])
        atoms.append([symbol, x, y, z])
    return atoms


def distance(a, b):
    return ((a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2 + (a[3] - b[3]) ** 2) ** 0.5


def find_hydroxyls(atoms):
    """Return a list of dicts describing each detected hydroxyl group
    (1-indexed atom numbers, matching the input .xyz order)."""
    hydroxyls = []
    for oi, o_atom in enumerate(atoms):
        if o_atom[0] != "O":
            continue
        h_idx = c_idx = None
        for ni, n_atom in enumerate(atoms):
            if ni == oi:
                continue
            d = distance(o_atom, n_atom)
            if n_atom[0] == "H" and d < OH_BOND_MAX:
                h_idx = ni
            elif n_atom[0] == "C" and d < CO_BOND_MAX:
                c_idx = ni
        if h_idx is None or c_idx is None:
            continue

        kind = "other"
        for ni, n_atom in enumerate(atoms):
            if n_atom[0] != "O" or ni == oi:
                continue
            if distance(atoms[c_idx], n_atom) < CARBONYL_BOND_MAX:
                kind = "carboxylic"
                break

        hydroxyls.append({
            "o_index": oi + 1, "h_index": h_idx + 1, "c_index": c_idx + 1,
            "kind": kind,
        })
    return hydroxyls


def write_xyz(atoms, path, comment=""):
    with open(path, "w") as f:
        f.write(f"{len(atoms)}\n{comment}\n")
        for symbol, x, y, z in atoms:
            f.write(f"{symbol:<2s} {x:14.7f} {y:14.7f} {z:14.7f}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Build a deprotonated starting geometry by removing "
                    "hydroxyl hydrogen(s) auto-classified as 'carboxylic' "
                    "or 'other' (e.g. phenolic).")
    parser.add_argument("--xyz", required=True, help="Neutral reference .xyz")
    parser.add_argument("--list-oh", action="store_true",
                         help="List detected hydroxyl groups and exit "
                              "(no files written)")
    parser.add_argument("--remove", nargs="+", choices=["carboxylic", "other"],
                         help="Which hydroxyl kind(s) to deprotonate "
                              "(one for a monoanion, both for a dianion)")
    parser.add_argument("--base-charge", type=int, default=0,
                         help="Total charge of the input --xyz (default 0, "
                              "i.e. neutral reference)")
    parser.add_argument("--output-dir",
                         help="Folder to create with the new structure.xyz "
                              "+ Turbomole 'coord' + CHARGE.txt")
    args = parser.parse_args()

    atoms = read_xyz(args.xyz)
    hydroxyls = find_hydroxyls(atoms)

    print(f"Detected {len(hydroxyls)} hydroxyl group(s) in '{args.xyz}':")
    for oh in hydroxyls:
        print(f"  O{oh['o_index']} (kind={oh['kind']}) - "
              f"H{oh['h_index']} - C{oh['c_index']}")

    if args.list_oh:
        return

    if not args.remove:
        raise SystemExit("Pass --remove (one or both of: carboxylic other) "
                          "or use --list-oh to just inspect.")

    kinds_found = {oh["kind"] for oh in hydroxyls}
    for kind in args.remove:
        if kind not in kinds_found:
            raise SystemExit(f"No hydroxyl of kind '{kind}' detected -- "
                              f"found kinds: {sorted(kinds_found)}")

    h_indices_to_remove = sorted(
        {oh["h_index"] for oh in hydroxyls if oh["kind"] in args.remove}
    )
    if len(h_indices_to_remove) != len(args.remove):
        raise SystemExit("Ambiguous match: more than one hydroxyl of the "
                          "same kind was detected -- inspect with --list-oh "
                          "and adjust this script's classification logic "
                          "before trusting it on this molecule.")

    new_atoms = [a for i, a in enumerate(atoms, start=1)
                 if i not in h_indices_to_remove]
    new_charge = args.base_charge - len(h_indices_to_remove)

    print(f"\nRemoving H{h_indices_to_remove} ({', '.join(args.remove)}) "
          f"-> {len(new_atoms)} atoms, total charge {new_charge:+d}")

    if not args.output_dir:
        raise SystemExit("Pass --output-dir to actually write the new state.")

    if os.path.exists(args.output_dir):
        raise FileExistsError(f"{args.output_dir} already exists -- refusing to overwrite.")
    os.makedirs(args.output_dir)

    xyz_out = os.path.join(args.output_dir, "structure.xyz")
    write_xyz(
        new_atoms, xyz_out,
        comment=f"charge={new_charge:+d}; removed H{h_indices_to_remove} "
                f"({', '.join(args.remove)}) from {args.xyz}",
    )

    coord_out = os.path.join(args.output_dir, "coord")
    script_dir = os.path.dirname(os.path.abspath(__file__))
    subprocess.run(
        ["python3", os.path.join(script_dir, "xyz_to_coord.py"),
         "--xyz", xyz_out, "--output", coord_out],
        check=True,
    )

    with open(os.path.join(args.output_dir, "CHARGE.txt"), "w") as f:
        f.write(f"{new_charge}\n")

    print(f"\nNew folder ready -> {args.output_dir}")
    print(f"  structure.xyz ({len(new_atoms)} atoms), coord, "
          f"CHARGE.txt ({new_charge:+d})")


if __name__ == "__main__":
    main()
